### ISSUE TITLE
ImportError: No module named 'statsmodels.tsa.johansen'

### ISSUE THREAD

**Issue by DanielAristidou** [mapsa/seminario-doc-2014#1]
ImportError: No module named 'statsmodels.tsa.johansen'

**Comment by saravanansaminathan** [comment]
Yes i too get same error. Any one please clarify it asap

**Comment by mapsa** [comment]
I've updated the code with the latest changes in statsmodels. Now these functions can be accessed from statsmodels.tsa.vector_ar.vecm.

**Comment by Kuntakimp** [comment]
> I've updated the code with the latest changes in statsmodels. Now these functions can be accessed from statsmodels.tsa.vector_ar.vecm.

I used" from stasmodel.tsa.vector_ar vecm import coint_johansen", however it shows "No module named vecm". How can I cope with it?

**Comment by mapsa** [comment]
are you missing a point? maybe you can try this:

from stasmodel.tsa.vector_ar.vecm import coint_johansen

**Comment by Mayanksoni20** [comment]
It does not work with "from stasmodel.tsa.vector_ar.vecm import coint_johansen"

**Comment by mapsa** [comment]
> from stasmodel.tsa.vector_ar.vecm import coint_johansen

How did you install statsmodel?
I installed it via conda:
conda install statsmodels

**Comment by saravanansaminathan** [comment]
> It does not work with "from stasmodel.tsa.vector_ar.vecm import coint_johansen"

Even I installed using pip install statsmodels 
It works fine in my environment

**Comment by Mayanksoni20** [comment]
Hey Mapsa, it worked after installing it with conda and doing some cleaning of my conda environment.Thank you
